tasks:
  - name: Install Conda
    init: |
      # Download and install Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      # Add Conda to PATH
      export PATH="$HOME/miniconda/bin:$PATH"
      # Initialize Conda for the shell
      conda init bash
      # Reload the shell to apply changes
      source ~/.bashrc